-- MySQL Script generated by MySQL Workbench
-- Mon Sep  6 23:16:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `shoes` ;

-- -----------------------------------------------------
-- Table `shoes`.`catogory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`catogory` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NULL DEFAULT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKr43af9ap4edm43mmtq01oddj6` (`username` ASC) VISIBLE,
  UNIQUE INDEX `UK6dotkott2kjsp8vw4d0m25fb7` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`customers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `firstname` VARCHAR(50) NULL DEFAULT NULL,
  `lastname` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(10) NULL DEFAULT NULL,
  `users_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKhnaqj709m7d4g1vmqr8blc6d1` (`users_id` ASC) VISIBLE,
  CONSTRAINT `FKhnaqj709m7d4g1vmqr8blc6d1`
    FOREIGN KEY (`users_id`)
    REFERENCES `shoes`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`discount` (
  `id` VARCHAR(255) NOT NULL,
  `percent` FLOAT NOT NULL,
  `deadline` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`products` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(255) NOT NULL,
  `createdby` VARCHAR(255) NOT NULL,
  `createddate` DATETIME NULL DEFAULT NULL,
  `deadline` DATETIME NULL DEFAULT NULL,
  `description` LONGTEXT NOT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `rating` INT NOT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `unitype` VARCHAR(255) NULL DEFAULT NULL,
  `category_id` BIGINT NULL DEFAULT NULL,
  `discount_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK2eai1d8yo225tbgcr61l7uh7e` (`category_id` ASC) VISIBLE,
  INDEX `FKdka7s7ph7n8erp8ryftjx8kch` (`discount_id` ASC) VISIBLE,
  CONSTRAINT `FK2eai1d8yo225tbgcr61l7uh7e`
    FOREIGN KEY (`category_id`)
    REFERENCES `shoes`.`catogory` (`id`),
  CONSTRAINT `FKdka7s7ph7n8erp8ryftjx8kch`
    FOREIGN KEY (`discount_id`)
    REFERENCES `shoes`.`discount` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`image` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `productid` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK4pw6o9gyseypangjr47ge5og6` (`productid` ASC) VISIBLE,
  CONSTRAINT `FK4pw6o9gyseypangjr47ge5og6`
    FOREIGN KEY (`productid`)
    REFERENCES `shoes`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`productdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`productdetail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `size` INT NOT NULL,
  `productid` BIGINT NULL DEFAULT NULL,
  `inventory` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKka10kh3nxxciojyl1x7x7xbmm` (`productid` ASC) VISIBLE,
  CONSTRAINT `FKka10kh3nxxciojyl1x7x7xbmm`
    FOREIGN KEY (`productid`)
    REFERENCES `shoes`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`orders` (
  `id` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `fullname` VARCHAR(255) NOT NULL,
  `modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `total` FLOAT NOT NULL,
  `customer_id` BIGINT NULL DEFAULT NULL,
  `payment_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKpxtb8awmi0dk6smoh2vp1litg` (`customer_id` ASC) VISIBLE,
  INDEX `FKag8ppnkjvx255gj7lm3m18wkj` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `FKag8ppnkjvx255gj7lm3m18wkj`
    FOREIGN KEY (`payment_id`)
    REFERENCES `shoes`.`payment` (`id`),
  CONSTRAINT `FKpxtb8awmi0dk6smoh2vp1litg`
    FOREIGN KEY (`customer_id`)
    REFERENCES `shoes`.`customers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`orderdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`orderdetail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `order_id` VARCHAR(255) NULL DEFAULT NULL,
  `productdetailid` BIGINT NULL DEFAULT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKfxkmvpbfxqect54pd7slj4ll9` (`order_id` ASC) VISIBLE,
  INDEX `FKemb0u1fj8a133xi73schcv8m4` (`productdetailid` ASC) VISIBLE,
  CONSTRAINT `FKemb0u1fj8a133xi73schcv8m4`
    FOREIGN KEY (`productdetailid`)
    REFERENCES `shoes`.`productdetail` (`id`),
  CONSTRAINT `FKfxkmvpbfxqect54pd7slj4ll9`
    FOREIGN KEY (`order_id`)
    REFERENCES `shoes`.`orders` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`type` (
  `id` VARCHAR(255) NOT NULL,
  `nametype` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`repository`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`repository` (
  `id` VARCHAR(255) NOT NULL,
  `datecreated` DATETIME NULL DEFAULT NULL,
  `price` FLOAT NOT NULL,
  `quantity` INT NOT NULL,
  `productdetailid` BIGINT NULL DEFAULT NULL,
  `type_id` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKhr36logtr3ab1op2n0ft1gvi7` (`productdetailid` ASC) VISIBLE,
  INDEX `FKhalpcmthea5ry4j2w16452xv3` (`type_id` ASC) VISIBLE,
  CONSTRAINT `FKhalpcmthea5ry4j2w16452xv3`
    FOREIGN KEY (`type_id`)
    REFERENCES `shoes`.`type` (`id`),
  CONSTRAINT `FKhr36logtr3ab1op2n0ft1gvi7`
    FOREIGN KEY (`productdetailid`)
    REFERENCES `shoes`.`productdetail` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`shopcart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`shopcart` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `customersid` BIGINT NULL DEFAULT NULL,
  `productdetailid` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKaxa2ldsbpop80m90sap00xslc` (`customersid` ASC) VISIBLE,
  INDEX `FKgaeld1612bt5wvgoipdyefr54` (`productdetailid` ASC) VISIBLE,
  CONSTRAINT `FKaxa2ldsbpop80m90sap00xslc`
    FOREIGN KEY (`customersid`)
    REFERENCES `shoes`.`customers` (`id`),
  CONSTRAINT `FKgaeld1612bt5wvgoipdyefr54`
    FOREIGN KEY (`productdetailid`)
    REFERENCES `shoes`.`productdetail` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`user_role` (
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `FKa68196081fvovjhkek5m97n3y` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKa68196081fvovjhkek5m97n3y`
    FOREIGN KEY (`role_id`)
    REFERENCES `shoes`.`role` (`id`),
  CONSTRAINT `FKj345gk1bovqvfame88rcx7yyx`
    FOREIGN KEY (`user_id`)
    REFERENCES `shoes`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shoes`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`wishlist` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT NULL DEFAULT NULL,
  `productid` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKk6lal9w7ut5e4xvta479rq06y` (`customer_id` ASC) VISIBLE,
  INDEX `FKmuppk1kk7nwi10yiho98emujv` (`productid` ASC) VISIBLE,
  CONSTRAINT `FKk6lal9w7ut5e4xvta479rq06y`
    FOREIGN KEY (`customer_id`)
    REFERENCES `shoes`.`customers` (`id`),
  CONSTRAINT `FKmuppk1kk7nwi10yiho98emujv`
    FOREIGN KEY (`productid`)
    REFERENCES `shoes`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
